config/routes.rb
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :restaurants, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, uniqueness: true, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(r_param)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def r_param
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_param)
    @review.restaurant_id = params[:restaurant_id]
    @review.save
    redirect_to restaurant_path(params[:restaurant_id])
  end

  def index
    @reviews = Review.where(restaurant_id: params[:restaurant_id])
  end

  private

  def review_param
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<h4><%= link_to "Add a restaurant", new_restaurant_path %></h4>
<p>Find me in app/views/restaurants/index.html.erb</p>
<% @restaurants.each do |r| %>
  <ul>
    <li><%= link_to r.name, restaurant_path(r) %></li>
    <li><%= r.address %></li>
    <li><%= r.phone_number %></li>
    <li><%= r.category %></li>
  </ul>
<% end %>

app/views/restaurants/new.html.erb
<div class="container">
<h1>Create Restaurant</h1>
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Add a Restaurant", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>
<ul>
  <li><%= @restaurant.name %></li>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.category %></li>
  <li><%= link_to "View Reviews", restaurant_reviews_path(params[:id]) %></li>
  <li><%= link_to "Add a review", new_restaurant_review_path(params[:id]) %></li>
</ul>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<% @reviews.each do |r| %>
  <ul>
    <li><%= r.content %></li>
    <li><%= r.rating %></li>
  </ul>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
<h1>Create review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add a Review", class: "btn btn-primary" %>
<% end %>
</div>